# main/CMakeLists.txt
idf_component_register(
    SRCS  
        bsp_adc.c
        bsp_led.c
        key.c
        main.c
        bsp_lcd.c
        image01.c
        wifi_scan.c
        wifi_station.c
        matrix.c
        font_library.c
        smartconfig.c
        http_client.c
    INCLUDE_DIRS 
        "."
    PRIV_REQUIRES 
        driver
        esp_adc
        esp_system
        hal
        esp_wifi
        wpa_supplicant
        esp_netif
        esp_event
        nvs_flash
    REQUIRES 
        esp_http_client
)
